In [15]:
import pandas as pd
import numpy as np
import re
import warnings

In [16]:
## Importing classification models

from sklearn.naive_bayes import MultinomialNB



In [17]:
data = pd.read_csv('Language Detection.csv')
data.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [18]:
# Separating the independent and dependent features
X = data['Text']
y = data['Language']

In [19]:
# Converting y into numerical values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [20]:
# Removing symobols numbers from the input text

text_list = []

for text in X:

    # Removing the symbols and numbers using regex
    text = re.sub(r'[!@#$(),n%^&*?:;~`0-9]', ' ', text)

    # Removing Square brackets
    text = re.sub(r'[[]]', ' ', text)

    # Converting it into lower order
    text = text.lower()

    # Appending the text into the new list
    text_list.append(text)
    

/tmp/ipykernel_3844/428090702.py:11: FutureWarning: Possible nested set at position 1
  text = re.sub(r'[[]]', ' ', text)


In [21]:
# Converting the input into numerical values using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(text_list).toarray()
X.shape

(10337, 34937)

In [22]:
# Splitting into training and testing datasets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
# Evaluate model function
from sklearn.metrics import accuracy_score

def evaluate_model(true, pred):
    acc = accuracy_score(true, pred)
    return acc



In [24]:
# # models = {
# #     "Logistic Regression": LogisticRegression(),
# #     "Guassian Naive Bayes": GaussianNB(),
# #     "Multinomial Naive Bayes": MultinomialNB(),
# #     "Bernoulli Naive Bayes": BernoulliNB()
# # }

# model_list=[]

# for i in range(len(list(models))):
#     model = list(models.values())[i]
#     model.fit(x_train, y_train)

#     # Predicting
#     y_train_pred = model.predict(x_train)
#     y_test_pred = model.predict(x_test)

#     # Evaluating train and testing data set
#     model_train_acc = evaluate_model(y_train_pred, y_train)

#     model_test_acc = evaluate_model(y_test_pred, y_test)

#     # Printing
#     print(list(models.keys())[i])
#     model_list.append(list(models.keys())[i])

#     print("Model Performance on training set")
#     print("Accuracy Score: {:.4f}".format(model_train_acc))

#     print("------------------------------------------")

#     print("Model Performance on testing set")
#     print("Accuracy Score: {:.4f}".format(model_test_acc))

#     print("------------------------------------------")




NameError: name 'model' is not defined

0.9753384912959381

In [26]:
from sklearn.base import BaseEstimator, TransformerMixin

class Remove(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        text_list = []
        for text in X:
            text = re.sub(r'[!@#$(),n%^&*?:;~`0-9]', ' ', text)

            # Removing Square brackets
            text = re.sub(r'[[]]', ' ', text)

                # Converting it into lower order
            text = text.lower()

                # Appending the text into the new list
            text_list.append(text)
        return text_list

In [27]:
from sklearn.feature_extraction.text import CountVectorizer


class BOW(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        cv = CountVectorizer()
        bow = cv.fit_transform(X).toarray()
        return bow

In [28]:
class Encoder(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        le = LabelEncoder()
        encoded_output = le.fit_transform(X)
        return encoded_output

In [29]:
import pandas as pd
data2 = pd.read_csv('Language Detection.csv')

In [30]:
from sklearn.preprocessing import LabelEncoder

encode = Encoder()
out = data2['Language']
encoded_output = encode.fit_transform(out)
ei = encoded_output
print(encoded_output)


[3 3 3 ... 9 9 9]


In [31]:
X = data['Text']
type(X)
X_array = np.array(X).reshape([-1, 1])
print(type(X_array))

<class 'numpy.ndarray'>


In [32]:
text_list = Remove()
text_list.fit(X)
new_list = text_list.transform(X)

print(type(new_list))

<class 'list'>


In [33]:
input = data['Text']
removeSymbols = Remove()
text_list = removeSymbols.fit_transform(X)



In [34]:
bow = BOW()
array = bow.fit_transform(text_list)
print(array)
print(array.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(10337, 34937)


In [35]:
data2 = pd.read_csv("Language Detection.csv")

In [36]:
data2.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [37]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ("remove", Remove()),
    ("bag of words", BOW())
])

input_array = pipe.fit_transform(data2['Text'])

In [38]:
print("Shape of input array = ",input_array.shape)
print(input_array)

Shape of input array =  (10337, 34937)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
from sklearn.preprocessing import TargetEncoder

pipe_output = Pipeline([
    ("label encoder", TargetEncoder())
])

In [56]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('input_pipeline', pipe, 'Text'),
    ('target_encoder', TargetEncoder(), ['Language'])

])

In [57]:
transformer.fit_transform(data2)

ValueError: Expected array-like (array or non-string sequence), got None